site_name: Almost Engineer Services
site_url: https://thealmostengineer.com
site_description: Providing technology and handyman services.
site_author: Kenny Robinson, @almostengr
copyright: Almost Engineer Services
google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr/almostengrwebsite
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8000

# Appearance
theme:
  name: null
  custom_dir: 'almostengrtheme'
  language: en
  social_user: "@almostengr"

  mainnav:
    - url: /about
      name: Services
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact

  carousel:
    - heading: Handyman Services
      description: Need a ceiling fan replaced? Need furniture assembled? We handle it all!
      imageurl: /images/kitchenisland_optimized.jpg
      buttonurl: /request
      buttontext: Request Tech Services
    - heading: Technology Services
      description: Need a change made to your website? Website not getting enough traffic? We cover all of these things!
      imageurl: /images/portfolio_tabcc2.jpg
      buttonurl: /request
      buttontext: Request Tech Services
    - heading: Blog and Portfolio
      description: To see our past work, checkout the blog where we share our experiences with and photos of our previous projects.
      imageurl: /images/writingcontent2.jpg
      buttonurl: /blog
      buttontext: See Past Projects

  featurette:
    - heading: Handyman Services
      description: Need that new furniture put together? Rotted trim that needs to be replaced? Is your toilet running even when nobody has used it? Hot summer days make you wish that you had a ceiling fan? We got you covered!
      buttonlink: /about#handyman-services
      imageurl: /images/patiofurniture_optimized.jpg
    - heading: Technology Services
      description: Need your business's website updated? Want to have Google Analytics set up on your website? Check out the Technology Services that we offer!
      buttonlink: /about#technology-services
      imageurl: /images/thermostat2.jpg
    - heading: Blog and Portfolio
      description: To see our past work, checkout out the blog where we describe and share our experience with and photos of previous projects.
      imageurl: /images/kitchenisland_optimized.jpg
      buttonlink: /blog

  footernav:
    - url: /about
      name: About
    - url: /uses
      name: Uses
    - url: /payment
      name: Make Payment
    - url: /request
      name: Request Service
    - url: /search
      name: Search
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact
    - url: /faq
      name: FAQ
    - url: /sitemap.xml
      name: Sitemap
    - url: /privacy
      name: Privacy

  services:
    - url: /blog/2020.07.12-ceiling-fan-installation-with-downrod
      name: Install Ceiling Fan
    - url: /blog/2019.07.30-reinforce-bookcase-with-plywood
      name: Bookcase Assembly
    - url: /blog/2020.07.21-front-yard-landscaping
      name: Landscaping
    - url: /blog/2018.07.21-how-to-replace-toilet-gasket-and-bolts
      name: Toilet Repair
    - url: /blog/2018.06.19-replace-optical-drive-in-pc/
      name: Computer Repair
    - url: /blog/2020.03.01-linux-training-session/
      name: Linux Training

  social:
    - type: github
      link: https://github.com/almostengr
    - type: instagram
      link: https://instagram.com/almostengr
    - type: twitter
      link: https://twitter.com/almostengr
    - type: youtube
      link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true
