site_name: The Almost Engineer
site_url: http://thealmostengineer.com
repo_url: https://github.com/almostengr
# site_favicon: 
repo_name: Github
site_description: The blog of Kenny R.
site_author: Kenny R, @almostengr

# Copyright
copyright: Copyright &copy; 2015-2019 Kenny R, The Almost Engineer

dev_addr: 192.168.57.111:8000

# Appearance
theme:
        name: null
        custom_dir: 'theme'
        language: en
        palette:
                primary: 'black'
                accent: 'brown'
        font: false
        logo:
                icon: 'user'
        feature:
                tabs: false

extra:
        social:
                - type: 'github'
                  link: 'https://github.com/almostengr'
                - type: 'instagram'
                  link: 'https://instagram.com/almostengr'
                - type: 'linkedin'
                  link: 'https://linkedin.com/in/krobinsontech'
                - type: 'twitter'
                  link: 'https://twitter.com/almostengr'
                - type: 'youtube'
                  link: 'https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1'
                - type: 'youtube'
                  link: 'https://www.youtube.com/channel/UCB7rvymUaUbbig3skv2zvCQ?sub_confirmation=1'
                        
use_directory_urls: true
strict: false

plugins:
        - search

nav:
- index.md
- contact.md
- Cheatsheets:
  - gitcheatsheet/README.md
  - linuxcheatsheet/README.md
# - privacy.md
- 2019:
  - blog/2019.12.21-switched-blog-from-drupal-to-mkdocs.md
  - blog/2019.12.20-blog-reverse-sort-with-mkdocs.md
  - blog/2019.11.24-takeaways-from-christopher-robin-movie.md
  - blog/2019.10.31-redirect-to-raspberry-pi-traffic-light.md
  - blog/2019.10.18-youtube.md
  - blog/2019.10.18-twitter.md
  - blog/2019.10.18-instagram.md
  - blog/2019.10.18-dash-cam.md
  - blog/2019.09.05-copying-infested-code.md
  - blog/2019.09-05-copying-infested-code.md
  - blog/2019.08.15-21-days-for-a-new-habit.md
  - blog/2019.07.23-markdown-my-words.md
  - blog/2019.07.04.when-deploying-before-testing.md
  - blog/2019.07.04-when-deploying-before-testing.md
  - blog/2019.07.03.squirrels-taught-me-about-women-and-food.md
  - blog/2019.07.03-squirrels-taught-me-about-women-and-food.md
  - blog/2019.06.16-7-reasons-i-can-do-that-without-the-app.md
  - blog/2019.06.13-3-benefits-of-doing-something-different-when-stuck.md
  - blog/2019.06.11.identify-electrical-circuits-and-label-breaker-panel.md
  - blog/2019.06.11-identify-electrical-circuits-and-label-breaker-panel.md
  - blog/2019.06.11-drupal-8-tutorial-series.md
  - blog/2019.05.09.automatically-publish-content-with-custom-module.md
  - blog/2019.05.09-automatically-publish-content-with-custom-module.md
  - blog/2019.05.09-7-steps-for-more-steps.md
  - blog/2019.05.07-how-to-install-chrome-on-ubuntu.md
  - blog/2019.05.02-4-steps-to-change-the-battery-in-nissan-altima-intelligent-key.md
  - blog/2019.04.30-read-an-audio-book.md
  - blog/2019.04.27-weber-charcoal-chimney-review-and-first-use.md
  - blog/2019.04.16-bird-is-the-word.md
  - blog/2019.04.10-how-to-start-a-garden-in-8-steps.md
  - blog/2019.04.05-set-up-gecko-driver-on-ubuntu.md
  - blog/2019.03.26-selenium-webdriver-photo-uploader-for-drupal-7.md
  - blog/2019.03.19-containers-vs-in-ground-gardening.md
  - blog/2019.03.16-manual-tree-branch-tear-down.md
  - blog/2019.03.11-sow,-a-planting-companion.md
  - blog/2019.03.11-building-raised-garden-beds-.md
  - blog/2019.03.05-use-gparted-to-partition-usb-drive.md
  - blog/2019.03.04-greens-from-the-winter-garden.md
  - blog/2019.02.27-drupal-8-tutorial-series.md
  - blog/2019.02.23-every-gardener-needs-a-journal.md
  - blog/2019.02.16-identify-circuits-and-label-breaker-panel.md
  - blog/2019.02.09-remove-water-from-car-trunk.md
  - blog/2019.01.29-set-timezone-on-ubuntu-18.04-server.md
- 2018:
  - blog/2018.11.10-archive-project-in-kdenlive.md
  - blog/2018.11.03-make-your-crockpot-smarter-with-a-timer.md
  - blog/2018.10.27-change-air-filter-on-2013-2018-5th-generation-nissan-altima.md
  - blog/2018.10.20-upgrade-ubuntu-16.04-to-ubuntu-18.04.md
  - blog/2018.09.22-upgrade-ubuntu-16.04-lts-to-18.04-lts-upgrade-no-commentary.md
  - blog/2018.08.28-power-on-wemo-switch-after-power-failure-with-home-assistant.md
  - blog/2018.08.14-install-hdhrviewer-plug-in-for-live-tv-on-plex-media-server.md
  - blog/2018.07.21-how-to-replace-toilet-gasket-and-bolts.md
  - blog/2018.07.14-install-seven-square-on-ubuntu.md
  - blog/2018.07.07.music-library-cleanup-with-fdupes.md
  - blog/2018.07.07-music-library-cleanup-with-fdupes.md
  - blog/2018.06.26-configure-hdhomerun-connect-with-kodi-on-ubuntu.md
  - blog/2018.06.19-replace-optical-drive-in-pc.md
  - blog/2018.06.12-setup-myq-with-home-assistant.md
  - blog/2018.06.05-configure-simplisafe-with-home-assistant.md
  - blog/2018.05.29-configure-dd-wrt-with-home-assistant.md
  - blog/2018.05.29-belkin-wemo-switch-unboxing.md
  - blog/2018.05.22-install-drush-on-ubuntu-16.04.md
  - blog/2018.05.15-configure-etckeeper-with-gitlab.md
  - blog/2018.05.08-redirect-to-home-assistant-using-apache.md
  - blog/2018.05.05-repair-leaking-faucet.md
  - blog/2018.05.01-upgrade-home-assistant.md
  - blog/2018.05.01-install-kodi-on-ubuntu.md
  - blog/2018.04.24-setup-hp-network-printer-on-ubuntu-16.04.md
  - blog/2018.04.17-setup-ssh-key-authentication.md
  - blog/2018.04.10-uninstall-plex-media-server-from-ubuntu-16.04.md
  - blog/2018.04.04-install-plex-on-ubuntu-16.04-server-or-desktop.md
  - blog/2018.03.27-kanban-board-in-drupal-7.md
  - blog/2018.03.13-install-postfix-to-use-gmail-as-smtp-server-on-ubuntu-16.04.md
  - blog/2018.03.13-install-home-assistant-on-ubuntu-16.04-vm.md
  - blog/2018.03.06-setup-ubuntu-16.04-on-virtualbox.md
  - blog/2018.02.27-install-virtualbox-on-ubuntu-16.04.md
  - blog/2018.02.27-install-oracle-virutalbox-on-ubuntu-16.04.md
  - blog/2018.02.20-install-webmin-on-ubuntu-16.04.md
  - blog/2018.02.13-use-twitter-and-rules-for-farmos-notifications.md
  - blog/2018.02.07-install-mysql-server-on-ubuntu-16.04.md
  - blog/2018.02.06-install-mysql-server.md
  - blog/2018.02.03.liftmaster-8500-review-1-year-later.md
  - blog/2018.02.03-liftmaster-8500-review,-1-year-later.md
  - blog/2018.01.23-raspitraffic-demo,-us-signaling.md
  - blog/2018.01.20-1-year-review-of-liftmaster-8500-with-myq-internet-gateway.md
  - blog/2018.01.19-snowfall-timelapse-in-montgomery,-al-january-16-17,-2018.md
  - blog/2018.01.16-raspberry-pi-first-run.md
  - blog/2018.01.16-raspberry-pi-first-run-and-installing-updates.md
  - blog/2018.01.16-install-samba-on-ubuntu-16.04.md
  - blog/2018.01.14-farmos-nws-2.0.md
- 2017:
  - blog/2017.04.13-raspberry-pi-traffic-light-control.md
  - blog/2017.04.03-linux-rm-argument-list-too-long.md
  - blog/2017.02.01-index.md
- 2016:
  - blog/2016.11.19-setup-ssh-on-openwrt.md
  - blog/2016.09.28-find-lines-longer-than-specified-length.md
  - blog/2016.08.21-faq-frequently-asked-questions.md
  - blog/2016.07.14-install-openwrt-on-linksys-wrt1900ac-v1.md
  - blog/2016.03.10-automating-ubuntu-14.04-automatic-updates.md
  - blog/2016.02.04-run-drupal-cron-via-bash-with-drush.md
  - blog/2016.02.04-automate-drupal-update-with-drush-via-shell-script.md
- 2015:
  - blog/2015.11.21-hdmi-sound-on-ubuntu-with-shuttle-ds61.md
  - blog/2015.10.30-use-session-variables-in-grails-domain-class.md
  - blog/2015.10.30-setup-ldap-on-ubuntu-10.04.md
  - blog/2015.10.30-select-list-of-us-states.md
  - blog/2015.10.30-sample-interview-question-unixlinux-experience.md
  - blog/2015.10.30-sample-interview-question-sqldatabase-experience-.md
  - blog/2015.10.30-rename-a-file-vb.net.md
  - blog/2015.10.30-migrate-drupal-installation-from-desktop-to-server.md
  - blog/2015.10.30-java-swap-values.md
  - blog/2015.10.30-java-count-up-and-down.md
  - blog/2015.10.30-installing-drupal-7-on-1and1-servers.md
  - blog/2015.10.30-image-rotator.md
  - blog/2015.10.30-how-to-keep-a-form-from-losing-focus-vb.net.md
  - blog/2015.10.30-grails-re-create-controller-and-views-for-updated-domain-class.md
  - blog/2015.10.30-find-lines-that-contain-greater-than-specified-number-of-characters-in-unix.md
  - blog/2015.10.30-automatically-creating-new-menu-items-drupal-7.md
  - blog/2015.10.30-asp.net-application-errors.md
  - blog/2015.10.21-how-to-disable-foreign-key-constraints-in-mysql.md
  - blog/2015.10.07-green-screen-with-flash-videos-in-windows-10.md
  - blog/2015.10.06-nsbe-mp-scholarship-module.md
  - blog/2015.09.13-university-of-alabama-chapter-of-the-national-society-of-black-engineers.md
  - blog/2015.09.13-tuscaloosa-area-black-chamber-of-commerce.md
  - blog/2015.09.13-naacp,-university-of-alabama-chapter.md
  - blog/2015.09.13-black-box-operations.md
  - blog/2015.09.04-oracle-holidays-without-stored-procedure-with-2-week-notification.md
  - blog/2015.06.28-search-engine-optimization.md
  - blog/2015.06.28-project-management-system.md
  - blog/2015.06.28-installing-drupal-7-on-1-and-1-web-hosting.md
  - blog/2015.06.28-how-to-synchronize-files-between-two-or-more-windows-computers.md
  - blog/2015.06.28-dont-use-click-here-in-links.md
  - blog/2015.06.24-services.md
  - blog/2015.06.24-privacy-policy--terms-of-use.md
  - blog/2015.06.24-about.md
