#site information
site_name: The Almost Engineer
site_url: http://thealmostengineer.com
site_description: The blog of Kenny Robinson.
site_author: Kenny Robinson, @almostengr
site_dir: site

google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr
repo_name: Github
remote_name: origin

# Copyright
copyright: Copyright &copy; 2015-2020 Kenny Robinson, The Almost Engineer

# Development server details
# dev_addr: 192.168.57.111:8000
# dev_addr: localhost:8000
dev_addr: 192.168.57.125:8000

# Appearance
theme:
        name: null
        custom_dir: 'theme'
        language: en
                        
use_directory_urls: true
strict: false

plugins:
        - search

markdown_extensions:
        - meta

nav:
  - index.md
  - blog.md
  - about.md
  - portfolio.md
  - resources.md
  - uses.md
  - contact.md
