site_name: The Almost Engineer
site_url: http://thealmostengineer.com
repo_url: https://github.com/almostengr
# site_favicon: 
repo_name: Github
site_description: The blog of Kenny R.
site_author: Kenny R, @almostengr

# Copyright
copyright: Copyright &copy; 2015-2019 Kenny R, The Almost Engineer

dev_addr: 192.168.57.111:8000

# Appearance
theme:
        name: null
        custom_dir: 'theme'
        language: en
        palette:
                primary: 'black'
                accent: 'brown'
        font: false
        logo:
                icon: 'user'
        feature:
                tabs: false

extra:
        social:
                - type: 'github'
                  link: 'https://github.com/almostengr'
                - type: 'instagram'
                  link: 'https://instagram.com/almostengr'
                - type: 'linkedin'
                  link: 'https://linkedin.com/in/krobinsontech'
                - type: 'twitter'
                  link: 'https://twitter.com/almostengr'
                - type: 'youtube'
                  link: 'https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1'
                - type: 'youtube'
                  link: 'https://www.youtube.com/channel/UCB7rvymUaUbbig3skv2zvCQ?sub_confirmation=1'
                        
use_directory_urls: true
strict: false

plugins:
        - search

nav:
- index.md
- contact.md
- 2019:
  - blog/2019-12-21-blog-reverse-sort-with-mkdocs.md
  - blog/2019-11-24-takeaways-from-christopher-robin-movie.md
  - blog/2019-09-05-copying-infested-code.md
  - blog/2019-07-23-markdown-my-words.md
  - blog/2019-07-04-when-deploying-before-testing.md
  - blog/2019-07-03-squirrels-taught-me-about-women-and-food.md
  - blog/2019-06-16-7-reasons-i-can-do-that-without-the-app.md
  - blog/2019-06-13-3-benefits-of-doing-something-different-when-stuck.md
  - blog/2019-04-10-how-to-start-a-garden-in-8-steps.md
  - blog/2019-03-19-containers-vs-in-ground-gardening.md
- 2018:
  - blog/2018-06-05-configure-simplisafe-with-home-assistant.md
  - blog/2018-02-03-liftmaster-8500-review-1-year-later.md
  - blog/2017.02.01-index.md
- Cheatsheets:
  - gitcheatsheet/README.md
  - linuxcheatsheet/README.md
- privacy.md
