#site information
site_name: The Almost Engineer
site_url: http://thealmostengineer.com
site_description: The blog of Kenny Robinson where he shares his thoughts and experiences.
site_author: Kenny Robinson, @almostengr
site_dir: site

google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr
repo_name: Github
remote_name: origin

# Copyright
copyright: Copyright &copy; 2015-2020 Kenny Robinson, The Almost Engineer

# Development server details
# dev_addr: 192.168.57.111:8000
# dev_addr: localhost:8000
dev_addr: 192.168.57.125:8000

# Appearance
theme:
        name: null
        custom_dir: 'theme'
        language: en
extra:
        social:
                - type: github
                  link: /github
                - type: instagram
                  link: /instagram
                - type: linkedin
                  link: /linkedin
                - type: stack-overflow
                  link: https://stackoverflow.com/users/12875554/almostengr
                - type: twitter
                  link: /twitter
                - type: youtube
                  link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1"
                - type: youtube
                  link: https://www.youtube.com/channel/UCB7rvymUaUbbig3skv2zvCQ?sub_confirmation=1
                        
use_directory_urls: true
strict: false

markdown_extensions:
        - meta

nav:
  - blog.md
  - portfolio.md
  - resources.md
  - uses.md
  - contact.md
  - About: index.md
  - search.md
