site_name: The Almost Engineer
site_url: http://thealmostengineer.com
repo_url: https://github.com/almostengr/almostengrwebsite
repo_name: Github
site_description: The blog of Kenny R.
site_author: Kenny R, @almostengr
copyright: The Almost Engineer
theme:
        name: mkdocs
use_directory_urls: true

