site_name: Almost Engineer Services
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson where he shares his thoughts and experiences.
site_author: Kenny Robinson, @almostengr
copyright: Almost Engineer Services
google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8000

# Appearance
theme:
  name: null
  custom_dir: 'almostengrtheme'
  language: en
  social_user: "@almostengr"
  
  mainnav:
    - url: /about
      name: Services
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact

  footernav:
    - url: /about
      name: About
    - url: /uses
      name: Uses
    - url: /payment
      name: Make Payment
    - url: /request
      name: Request Service
    - url: /search
      name: Search
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact
    - url: /faq
      name: FAQ
    - url: /sitemap.xml
      name: Sitemap
    - url: /privacy
      name: Privacy

  services:
    - url: /blog/2020.07.12-ceiling-fan-installation-with-downrod
      name: Install Ceiling Fan
    - url: /blog/2019.07.30-reinforce-bookcase-with-plywood
      name: Bookcase Assembly
    - url: /blog/2020.07.21-front-yard-landscaping
      name: Landscaping
    - url: /blog/2018.07.21-how-to-replace-toilet-gasket-and-bolts
      name: Toilet Repair
    - url: /blog/2018.06.19-replace-optical-drive-in-pc/
      name: Computer Repair
    - url: /blog/2020.03.01-linux-training-session/
      name: Linux Training

  social:
    - type: github
      link: https://github.com/almostengr
    - type: instagram
      link: https://instagram.com/almostengr
    - type: twitter
      link: https://twitter.com/almostengr
    - type: youtube
      link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1

  serviceareas: [
    'Montgomery County, Alabama', 
    'Elmore County, Alabama', 
    'Autauga County, Alabama'
    ]

use_directory_urls: true
strict: false

# markdown_extensions:
  # - meta

plugins:
  - search
  - minify: 
      minify_html: true
