site_name: Light Show
site_url: https://lightshow.thealmostengineer.com
copyright: Copyright &copy; 2010-2023 Kenny Robinson

# repository information
remote_name: origin
remote_branch: websitelights

# Development server details
dev_addr: 192.168.2.103:8000

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true
