<?php 

/**
 *
 * implements hook_cron()
 */
function almostengr_cron() {
  almostengr_publish_posts();
} // end function

/**
 *
 * Publish any of the article nodes that have a created date before the current time.
 */
function almostengr_publish_posts() {
  $result = db_query("select nid from {node} where created <= :datetime and promote = :promote and status = :status and type = :type",
	array(":datetime" => REQUEST_TIME, ":promote" => 1, ":status" => 0, ":type" => "article"));
  foreach($result as $row) {
    $article = node_load($row->nid);
    $article->status = 1; // update the status
    $article->comment = 2; // enable comments
    node_save($article); // save article
  } // end foreach
} // end function

