<?php

/**
 * Publish articles that have their post date in the past
 */ 
function almostengr_publish_articles() {
  // $query = "update {node} set status = 1, changed = unix_timestamp() where type = 'article' and created <= unix_timestamp and promote = 1";
  $query = "select nid from {node} where status = 0 and created <= unix_timestamp() and promote = 1 and type = 'article'";
  $result = db_query($query);

  foreach($result as $row) {
    $article = node_load($row->nid);
    $article->status = 1;
    node_save($article);
    watchdog('almostengr', 'Article ' . $row->nid . ' has been published.', array(), WATCHDOG_INFO, NULL);
  }
}

/**
 * Removes the show name from the title of new articles
 */
function almostengr_node_presave($node) {
  // remove show name from title of node
  $node->title = str_replace('| Almost Engineered Tech', '', $node->title);
  $node->title = str_replace('| Almost Afro Engineered', '', $node->title);
}

