site_name: ex
site_url: https://speak.thealmostengineer.com
repo_url: https://github.com/almostengr/almostengrwebsite
site_author: Kenny Robinson
copyright: "&copy; 2026 Kenny Robinson"
use_directory_urls: true

# theme:
#   name: material
theme:
  name: null
  custom_dir: 'theme'
  language: en

strict: false

plugins:
  - minify:
      minify_html: true

# nav:
#   - "index.md"
#   - A.I. for Small Business:
#     - "a-i-for-small-business/index.md"
#     - "a-i-for-small-business/responsibleuse.md"
#     - "a-i-for-small-business/responsibleus2.md"
#     - "a-i-for-small-business/responsibleuse3.md"
#     - "a-i-for-small-business/structure.md"
#     - "a-i-for-small-business/structure2.md"
#     - "a-i-for-small-business/trustbutverify.md"
#     - "a-i-for-small-business/index.md"
#     - "a-i-for-small-business/index.md"
