CREATE TABLE IF NOT EXISTS songrequest (
  id INT NOT NULL AUTO_INCREMENT,
  sequenceName VARCHAR(255) NOT NULL,
  createdTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdIpAddress VARCHAR(255) NOT NULL,
  modifiedTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modifiedIpAddress VARCHAR(255) NOT NULL,
  played BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);
