site_name: The Almost Engineer
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Copyright &copy; 2010-2022 Kenny Robinson

# repository information
# repo_url: https://github.com/almostengr/almostengrwebsite
# repo_name: almostengrwebsite
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.1.103:8000

# Appearance
theme:
  name: material
  custom_dir: 'theme-overrides'
  language: en
  static_templates:
    - 404.html
  font:
    text: Ubuntu
    code: Ubuntu Mono
  palette:
#     - scheme: default
#       primary: black
#       accent: red
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blue gray
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - navigation.tracking

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true
  - search:
      lang: en
      min_search_length: 3

extra: 
  analytics:
    provider: google  
    property: 
  social: 
    - icon: fontawesome/brands/github 
      link: https://github.com/almostengr
      name: almostengr on Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/almostengr
      name: "@almostengr on Instagram"
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/12875554/almostengr
      name: almostengr on StackOverflow
    - icon: fontawesome/brands/tiktok
      name: almostengr on TikTok
      link: https://www.tiktok.com/@almostengr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/almostengr
      name: "@almostengr on Twitter"
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/RobinsonHandyandTechnologyServices?sub_confirmation=1
      name: Home Improvement with RHT Services on YouTube
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC4xp-TEEIAL-4XtMVvfRaQw?sub_confirmation=1
      name: Tech Talk with RHT Services on YouTube
