site_name: The Almost Engineer | The Blog of Kenny Robinson
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Copyright &copy; Kenny Robinson

# repository information
# repo_url: https://github.com/almostengr/almostengrwebsite
# repo_name: almostengrwebsite
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 10.10.10.104:8000

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  language: en
  static_templates:
    - 404.html
use_directory_urls: true
strict: false

plugins:
  - rss:  
    rss_feed_enabled: false
  - minify:
      minify_html: true

# hooks:
  # - hooks/json_export.py
