site_name: The Almost Engineer
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Copyright &copy; 2010-2023 Kenny Robinson

# repository information
# repo_url: https://github.com/almostengr/almostengrwebsite
# repo_name: almostengrwebsite
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 10.10.10.104:8000

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  language: en
  jumbotron: default #christmas
  static_templates:
    - 404.html
use_directory_urls: true
strict: false

plugins:
  # - minify:
  #     minify_html: true
