name: Blog Precipitation Data

on:
  schedule:
    - cron: '15 06 * * *'

jobs:
  getdata:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    
    - name: Get Weather Data
      run: dotnet run --project Almostengr.AlmostengrWebsite.Precipitation/Almostengr.AlmostengrWebsite.Precipitation.csproj

    - name: Run commit on files
      run: bash scripts/ghcommit.sh
