name: Build branch on push

on:
  push: 
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: buildout
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository ${GITHUB_REF##*/}
      uses: actions/checkout@v2
      with: 
        repository: ${GITHUB_REF##*/}

    - name: Installing Python
      run:  python -m pip install --upgrade pip

    - name: Installing Mkdocs
      run:  python -m pip install mkdocs
        
    - name: Building website
      run:  python -m mkdocs build
