name: Build branch on push

on:
  push: 
    branches:
      - '*'
      - '!master'
      - '!gh-pages'

  pull_request:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'

# help with variables https://github.com/actions/checkout

jobs:
  build:
    name: buildout
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository ${{ github.event.pull_request.head.sha }}
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Installing python3
      run:  /usr/bin/python3 -m pip install --upgrade pip
    
    - name: Installing setuptools
      run: /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Installing Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin
        
    - name: Building website
      run:  /usr/bin/python3 -m mkdocs build
