name: Deploy from master

on:
        push: 
                branches:
                        - master

        pull_request:
                branches:
                        - master

jobs:
        build:
                name: buildout
                runs-on: ubuntu-latest

                steps:
                - name: Checkout latest master
                  uses: actions/checkout@v2
                  with: 
                        repository: almostengr/almostengrwebsite

                - name: Installing Python
                  run:  python -m pip install --upgrade pip
          
                - name: Installing Mkdocs
                  run: pip install mkdocs
                   
                - name: Building static site
                  run: python -m mkdocs gh-deploy
