name: Deploy from master

on:
        push: 
                branches:
                        - master

        pull_request:
                branches:
                        - master

jobs:
        build:
                name: buildout
                runs-on: ubuntu-latest

                steps:
                - name: checkout repo
                  uses: almostengr/almostengrwebsite@master
