name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  prod_release:
    name: Production release
    runs-on: ubuntu-latest

    steps:
    - name: Check out main branch
      uses: actions/checkout@master
      with:
        ref: main

    - run: /usr/bin/python3 -m pip install --upgrade setuptools
    - run: /usr/bin/python3 -m pip install --upgrade mkdocs
    - run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - run: git fetch -p

    - run: /usr/bin/python3 -m mkdocs build -f presentations/mkdocs.yml build/presentations
      name: Build presentations

    - run: /usr/bin/python3 -m mkdocs build -f website/mkdocs.yml build/website
      name: Build website

    - run: |
        website/scripts/generate_rss.sh
      name: Generating RSS files

    - name: Deploy presentations
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT_NUMBER }}
        source: "build/presentations/*"
        target: ${{ secrets.TALKS_DIRECTORY }}
        key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy website
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT_NUMBER }}
        source: "build/website/*"
        target: ${{ secrets.WWW_DIRECTORY }}
        key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy website RSS files
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT_NUMBER }}
        source: "dadlife.rss.xml,electronics.rss.xml,tech.rss.xml,webdevelopment.rss.xml"
        target: ${{ secrets.WWW_DIRECTORY }}
        key: ${{ secrets.PRIVATE_KEY }}
