site_name: The Almost Engineer
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Kenny Robinson
google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr/almostengrwebsite
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8000

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  # custom_dir: 'apitheme'
  language: en
  social_user: "@almostengr"
  mainnav:
    - url: /blog
      name: Blog
    - url: /portfolio
      name: Portfolio
    - url: /resources
      name: Resources
    - url: /uses
      name: Uses
    - url: /about
      name: About
    - url: /contact
      name: Contact
    # - url: /donate
    #   name: Donate
  # sitemessage
    # - heading: heading
    #   detail: detail
    #   bgcolor: bg-primary
    #   textcolor: text-light
  # homemessage:
  #   - heading: heading
  #     detail: detail
  #     bgcolor: bg-primary
  #     textcolor: text-light
  homepagecategory:
    - name: Technology
      url: /technology
    - name: Handyman
      url: /handyman
    - name: Speaking
      url: /speaking
    - name: Gardening
      url: /gardening
  footernav:
    - url: /about
      name: About
    - url: /uses
      name: Uses
    # - url: /search
    #   name: Search
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact
    - url: /sitemap.xml
      name: Sitemap
    - url: /privacy
      name: Privacy
    # - url: /donate
    #   name: Donate
  topics:
    - link: /handyman
      name: DIY/Handyman
    - link: /technology
      name: Technology
    - link: /speaking
      name: Speaking
    - link: /gardening
      name: Gardening
    - link: /resources
      name: Tech Resources
    - link: /portfolio
      name: Portfolio
  social:
    - type: github
      link: https://github.com/almostengr
      name: GitHub
    - type: instagram
      link: https://instagram.com/almostengr
      name: Instagram
    - type: linkedin
      link: https://www.linkedin.com/in/krobinsontech
      name: LinkedIn
    - type: twitter
      link: https://twitter.com/almostengr
      name: Twitter
    - type: youtube
      link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1
      name: YouTube
  about:
    - heading: About
    # - detail: 
  mobilelinks:
    - name: RHT Services LLC
      url: https://rhtservices.net
    - name: Follow Me On Github
      url: https://github.com/almostengr
    - name: Follow Me On Instagram
      url: https://instagram.com/almostengr
    - name: Follow Me On Twitter
      url: https://twitter.com/almostengr
    - name: Subscribe To My YouTube Channel
      url: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true
  - search:
      lang: en