site_name: Kenny The Almost Engineer
site_url: https://thealmostengineer.com
site_description: Blog for Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Kenny Robinson
google_analytics: ['UA-64643711-1', 'thealmostengineer.com']

# repository information
repo_url: https://github.com/almostengr/almostengrwebsite
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8000

# Appearance
theme:
  name: null
  custom_dir: 'theme'
  language: en
  social_user: "@almostengr"
  # sitemessage
    # - heading: heading
    #   detail: detail
    #   bgcolor: bg-primary
    #   textcolor: text-light
  # homemessage:
  #   - heading: heading
  #     detail: detail
  #     bgcolor: bg-primary
  #     textcolor: text-light
  jumbotron:
    - heading: heading
      detail: detail
      url: #
      background_image: "/images/jumbotron.jpg"
      textcolor: text-warning
      buttoncolor: btn-warning
  mainnav:
    - url: /blog
      name: Blog
    - url: /uses
      name: Uses
    - url: /donate
      name: Donate
    - url: /about
      name: About
  featurette:
    - heading: Blog
      description: To see our past work, checkout out the blog where we describe and share our experience with and photos of previous projects.
      imageurl: /images/kitchenisland_optimized.jpg
      buttonlink: /blog
  footernav:
    - url: /about
      name: About
    - url: /uses
      name: Uses
    - url: /search
      name: Search
    - url: /blog
      name: Blog
    - url: /contact
      name: Contact
    - url: /faq
      name: FAQ
    - url: /sitemap.xml
      name: Sitemap
    - url: /privacy
      name: Privacy
    - url: /donate
      name: Donate
  social:
    - type: github
      link: https://github.com/almostengr
    - type: instagram
      link: https://instagram.com/almostengr
    - type: twitter
      link: https://twitter.com/almostengr
    - type: youtube
      link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true